title: Book-Battles
description: "August 2023 to June 2024"
owner_name: Nikki Hekmat
github_username: nikkihekmat
github_repo: "Nighthawk-Pages"
baseurl: "/frontend_shared"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/Ankit-177"}
    - { platform: github, user_url: "https://github.com/varunm532"}
    - { platform: github, user_url: "https://github.com/nikkihekmat"}
    - { platform: github, user_url: "https://github.com/mhr77777"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
